// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package query

import (
	"time"

	"github.com/google/uuid"
)

type User struct {
	// GUID пользователя
	Guid uuid.UUID
	// Имя пользователя
	Name string
	// Место работы
	Occupation string
	// Признак удален ли пользователь
	IsDeleted bool
	// Дата создания
	CreatedAt time.Time
	// Дата обновления
	UpdatedAt time.Time
}
