// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package query

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type LoggedIn struct {
	// Гуид пользователя
	UserGuid uuid.UUID
	// Время окончания авторизации
	Expiry sql.NullTime
}

type User struct {
	// GUID пользователя
	Guid uuid.UUID
	// Имя пользователя
	Name string
	// Место работы
	Occupation string
	// Признак удален ли пользователь
	IsDeleted bool
	// Дата создания
	CreatedAt time.Time
	// Дата обновления
	UpdatedAt time.Time
	// Хэш пароля
	Pwd string
	// Email
	Email string
}
