// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orders.sql

package query

import (
	"context"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const createOrder = `-- name: CreateOrder :exec
INSERT INTO orders (
        guid,
        user_guid,
        number,
        amount,
        status,
        created_at,
        updated_at
    )
VALUES ($1, $2, $3, $4, $5, now(), now())
`

type CreateOrderParams struct {
	Guid     uuid.UUID
	UserGuid uuid.UUID
	Number   string
	Amount   decimal.Decimal
	Status   OrderStatus
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) error {
	_, err := q.exec(ctx, q.createOrderStmt, createOrder,
		arg.Guid,
		arg.UserGuid,
		arg.Number,
		arg.Amount,
		arg.Status,
	)
	return err
}
