// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/loads"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/runtime/security"
	"github.com/go-openapi/spec"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"otusgruz/internal/restapi/operations/other"
	"otusgruz/internal/restapi/operations/user_c_r_u_d"
)

// NewRestServerAPI creates a new RestServer instance
func NewRestServerAPI(spec *loads.Document) *RestServerAPI {
	return &RestServerAPI{
		handlers:            make(map[string]map[string]http.Handler),
		formats:             strfmt.Default,
		defaultConsumes:     "application/json",
		defaultProduces:     "application/json",
		customConsumers:     make(map[string]runtime.Consumer),
		customProducers:     make(map[string]runtime.Producer),
		PreServerShutdown:   func() {},
		ServerShutdown:      func() {},
		spec:                spec,
		useSwaggerUI:        false,
		ServeError:          errors.ServeError,
		BasicAuthenticator:  security.BasicAuth,
		APIKeyAuthenticator: security.APIKeyAuth,
		BearerAuthenticator: security.BearerAuth,

		JSONConsumer: runtime.JSONConsumer(),

		JSONProducer: runtime.JSONProducer(),

		UsercrudDeleteUserGUIDHandler: user_c_r_u_d.DeleteUserGUIDHandlerFunc(func(params user_c_r_u_d.DeleteUserGUIDParams) middleware.Responder {
			return middleware.NotImplemented("operation user_c_r_u_d.DeleteUserGUID has not yet been implemented")
		}),
		OtherGetAuthHandler: other.GetAuthHandlerFunc(func(params other.GetAuthParams) middleware.Responder {
			return middleware.NotImplemented("operation other.GetAuth has not yet been implemented")
		}),
		OtherGetHealthHandler: other.GetHealthHandlerFunc(func(params other.GetHealthParams) middleware.Responder {
			return middleware.NotImplemented("operation other.GetHealth has not yet been implemented")
		}),
		UsercrudGetUserGUIDHandler: user_c_r_u_d.GetUserGUIDHandlerFunc(func(params user_c_r_u_d.GetUserGUIDParams) middleware.Responder {
			return middleware.NotImplemented("operation user_c_r_u_d.GetUserGUID has not yet been implemented")
		}),
		UsercrudPatchUserGUIDHandler: user_c_r_u_d.PatchUserGUIDHandlerFunc(func(params user_c_r_u_d.PatchUserGUIDParams) middleware.Responder {
			return middleware.NotImplemented("operation user_c_r_u_d.PatchUserGUID has not yet been implemented")
		}),
		OtherPostLoginHandler: other.PostLoginHandlerFunc(func(params other.PostLoginParams) middleware.Responder {
			return middleware.NotImplemented("operation other.PostLogin has not yet been implemented")
		}),
		OtherPostSignupHandler: other.PostSignupHandlerFunc(func(params other.PostSignupParams) middleware.Responder {
			return middleware.NotImplemented("operation other.PostSignup has not yet been implemented")
		}),
		UsercrudPostUserHandler: user_c_r_u_d.PostUserHandlerFunc(func(params user_c_r_u_d.PostUserParams) middleware.Responder {
			return middleware.NotImplemented("operation user_c_r_u_d.PostUser has not yet been implemented")
		}),
	}
}

/*RestServerAPI API сервиса Otusgruz */
type RestServerAPI struct {
	spec            *loads.Document
	context         *middleware.Context
	handlers        map[string]map[string]http.Handler
	formats         strfmt.Registry
	customConsumers map[string]runtime.Consumer
	customProducers map[string]runtime.Producer
	defaultConsumes string
	defaultProduces string
	Middleware      func(middleware.Builder) http.Handler
	useSwaggerUI    bool

	// BasicAuthenticator generates a runtime.Authenticator from the supplied basic auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BasicAuthenticator func(security.UserPassAuthentication) runtime.Authenticator

	// APIKeyAuthenticator generates a runtime.Authenticator from the supplied token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	APIKeyAuthenticator func(string, string, security.TokenAuthentication) runtime.Authenticator

	// BearerAuthenticator generates a runtime.Authenticator from the supplied bearer token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BearerAuthenticator func(string, security.ScopedTokenAuthentication) runtime.Authenticator

	// JSONConsumer registers a consumer for the following mime types:
	//   - application/json
	JSONConsumer runtime.Consumer

	// JSONProducer registers a producer for the following mime types:
	//   - application/json
	JSONProducer runtime.Producer

	// UsercrudDeleteUserGUIDHandler sets the operation handler for the delete user GUID operation
	UsercrudDeleteUserGUIDHandler user_c_r_u_d.DeleteUserGUIDHandler
	// OtherGetAuthHandler sets the operation handler for the get auth operation
	OtherGetAuthHandler other.GetAuthHandler
	// OtherGetHealthHandler sets the operation handler for the get health operation
	OtherGetHealthHandler other.GetHealthHandler
	// UsercrudGetUserGUIDHandler sets the operation handler for the get user GUID operation
	UsercrudGetUserGUIDHandler user_c_r_u_d.GetUserGUIDHandler
	// UsercrudPatchUserGUIDHandler sets the operation handler for the patch user GUID operation
	UsercrudPatchUserGUIDHandler user_c_r_u_d.PatchUserGUIDHandler
	// OtherPostLoginHandler sets the operation handler for the post login operation
	OtherPostLoginHandler other.PostLoginHandler
	// OtherPostSignupHandler sets the operation handler for the post signup operation
	OtherPostSignupHandler other.PostSignupHandler
	// UsercrudPostUserHandler sets the operation handler for the post user operation
	UsercrudPostUserHandler user_c_r_u_d.PostUserHandler

	// ServeError is called when an error is received, there is a default handler
	// but you can set your own with this
	ServeError func(http.ResponseWriter, *http.Request, error)

	// PreServerShutdown is called before the HTTP(S) server is shutdown
	// This allows for custom functions to get executed before the HTTP(S) server stops accepting traffic
	PreServerShutdown func()

	// ServerShutdown is called when the HTTP(S) server is shut down and done
	// handling all active connections and does not accept connections any more
	ServerShutdown func()

	// Custom command line argument groups with their descriptions
	CommandLineOptionsGroups []swag.CommandLineOptionsGroup

	// User defined logger function.
	Logger func(string, ...interface{})
}

// UseRedoc for documentation at /docs
func (o *RestServerAPI) UseRedoc() {
	o.useSwaggerUI = false
}

// UseSwaggerUI for documentation at /docs
func (o *RestServerAPI) UseSwaggerUI() {
	o.useSwaggerUI = true
}

// SetDefaultProduces sets the default produces media type
func (o *RestServerAPI) SetDefaultProduces(mediaType string) {
	o.defaultProduces = mediaType
}

// SetDefaultConsumes returns the default consumes media type
func (o *RestServerAPI) SetDefaultConsumes(mediaType string) {
	o.defaultConsumes = mediaType
}

// SetSpec sets a spec that will be served for the clients.
func (o *RestServerAPI) SetSpec(spec *loads.Document) {
	o.spec = spec
}

// DefaultProduces returns the default produces media type
func (o *RestServerAPI) DefaultProduces() string {
	return o.defaultProduces
}

// DefaultConsumes returns the default consumes media type
func (o *RestServerAPI) DefaultConsumes() string {
	return o.defaultConsumes
}

// Formats returns the registered string formats
func (o *RestServerAPI) Formats() strfmt.Registry {
	return o.formats
}

// RegisterFormat registers a custom format validator
func (o *RestServerAPI) RegisterFormat(name string, format strfmt.Format, validator strfmt.Validator) {
	o.formats.Add(name, format, validator)
}

// Validate validates the registrations in the RestServerAPI
func (o *RestServerAPI) Validate() error {
	var unregistered []string

	if o.JSONConsumer == nil {
		unregistered = append(unregistered, "JSONConsumer")
	}

	if o.JSONProducer == nil {
		unregistered = append(unregistered, "JSONProducer")
	}

	if o.UsercrudDeleteUserGUIDHandler == nil {
		unregistered = append(unregistered, "user_c_r_u_d.DeleteUserGUIDHandler")
	}
	if o.OtherGetAuthHandler == nil {
		unregistered = append(unregistered, "other.GetAuthHandler")
	}
	if o.OtherGetHealthHandler == nil {
		unregistered = append(unregistered, "other.GetHealthHandler")
	}
	if o.UsercrudGetUserGUIDHandler == nil {
		unregistered = append(unregistered, "user_c_r_u_d.GetUserGUIDHandler")
	}
	if o.UsercrudPatchUserGUIDHandler == nil {
		unregistered = append(unregistered, "user_c_r_u_d.PatchUserGUIDHandler")
	}
	if o.OtherPostLoginHandler == nil {
		unregistered = append(unregistered, "other.PostLoginHandler")
	}
	if o.OtherPostSignupHandler == nil {
		unregistered = append(unregistered, "other.PostSignupHandler")
	}
	if o.UsercrudPostUserHandler == nil {
		unregistered = append(unregistered, "user_c_r_u_d.PostUserHandler")
	}

	if len(unregistered) > 0 {
		return fmt.Errorf("missing registration: %s", strings.Join(unregistered, ", "))
	}

	return nil
}

// ServeErrorFor gets a error handler for a given operation id
func (o *RestServerAPI) ServeErrorFor(operationID string) func(http.ResponseWriter, *http.Request, error) {
	return o.ServeError
}

// AuthenticatorsFor gets the authenticators for the specified security schemes
func (o *RestServerAPI) AuthenticatorsFor(schemes map[string]spec.SecurityScheme) map[string]runtime.Authenticator {
	return nil
}

// Authorizer returns the registered authorizer
func (o *RestServerAPI) Authorizer() runtime.Authorizer {
	return nil
}

// ConsumersFor gets the consumers for the specified media types.
// MIME type parameters are ignored here.
func (o *RestServerAPI) ConsumersFor(mediaTypes []string) map[string]runtime.Consumer {
	result := make(map[string]runtime.Consumer, len(mediaTypes))
	for _, mt := range mediaTypes {
		switch mt {
		case "application/json":
			result["application/json"] = o.JSONConsumer
		}

		if c, ok := o.customConsumers[mt]; ok {
			result[mt] = c
		}
	}
	return result
}

// ProducersFor gets the producers for the specified media types.
// MIME type parameters are ignored here.
func (o *RestServerAPI) ProducersFor(mediaTypes []string) map[string]runtime.Producer {
	result := make(map[string]runtime.Producer, len(mediaTypes))
	for _, mt := range mediaTypes {
		switch mt {
		case "application/json":
			result["application/json"] = o.JSONProducer
		}

		if p, ok := o.customProducers[mt]; ok {
			result[mt] = p
		}
	}
	return result
}

// HandlerFor gets a http.Handler for the provided operation method and path
func (o *RestServerAPI) HandlerFor(method, path string) (http.Handler, bool) {
	if o.handlers == nil {
		return nil, false
	}
	um := strings.ToUpper(method)
	if _, ok := o.handlers[um]; !ok {
		return nil, false
	}
	if path == "/" {
		path = ""
	}
	h, ok := o.handlers[um][path]
	return h, ok
}

// Context returns the middleware context for the rest server API
func (o *RestServerAPI) Context() *middleware.Context {
	if o.context == nil {
		o.context = middleware.NewRoutableContext(o.spec, o, nil)
	}

	return o.context
}

func (o *RestServerAPI) initHandlerCache() {
	o.Context() // don't care about the result, just that the initialization happened
	if o.handlers == nil {
		o.handlers = make(map[string]map[string]http.Handler)
	}

	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/user/{guid}"] = user_c_r_u_d.NewDeleteUserGUID(o.context, o.UsercrudDeleteUserGUIDHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/auth"] = other.NewGetAuth(o.context, o.OtherGetAuthHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/health"] = other.NewGetHealth(o.context, o.OtherGetHealthHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/user/{guid}"] = user_c_r_u_d.NewGetUserGUID(o.context, o.UsercrudGetUserGUIDHandler)
	if o.handlers["PATCH"] == nil {
		o.handlers["PATCH"] = make(map[string]http.Handler)
	}
	o.handlers["PATCH"]["/user/{guid}"] = user_c_r_u_d.NewPatchUserGUID(o.context, o.UsercrudPatchUserGUIDHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/login"] = other.NewPostLogin(o.context, o.OtherPostLoginHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/signup"] = other.NewPostSignup(o.context, o.OtherPostSignupHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/user"] = user_c_r_u_d.NewPostUser(o.context, o.UsercrudPostUserHandler)
}

// Serve creates a http handler to serve the API over HTTP
// can be used directly in http.ListenAndServe(":8000", api.Serve(nil))
func (o *RestServerAPI) Serve(builder middleware.Builder) http.Handler {
	o.Init()

	if o.Middleware != nil {
		return o.Middleware(builder)
	}
	if o.useSwaggerUI {
		return o.context.APIHandlerSwaggerUI(builder)
	}
	return o.context.APIHandler(builder)
}

// Init allows you to just initialize the handler cache, you can then recompose the middleware as you see fit
func (o *RestServerAPI) Init() {
	if len(o.handlers) == 0 {
		o.initHandlerCache()
	}
}

// RegisterConsumer allows you to add (or override) a consumer for a media type.
func (o *RestServerAPI) RegisterConsumer(mediaType string, consumer runtime.Consumer) {
	o.customConsumers[mediaType] = consumer
}

// RegisterProducer allows you to add (or override) a producer for a media type.
func (o *RestServerAPI) RegisterProducer(mediaType string, producer runtime.Producer) {
	o.customProducers[mediaType] = producer
}

// AddMiddlewareFor adds a http middleware to existing handler
func (o *RestServerAPI) AddMiddlewareFor(method, path string, builder middleware.Builder) {
	um := strings.ToUpper(method)
	if path == "/" {
		path = ""
	}
	o.Init()
	if h, ok := o.handlers[um][path]; ok {
		o.handlers[um][path] = builder(h)
	}
}
