// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CreatedOrderData Параметры созданного заказа
//
// swagger:model CreatedOrderData
type CreatedOrderData struct {

	// Номер заказа
	// Required: true
	OrderNumber string `json:"order_number"`

	// Статус заказа
	// Required: true
	Status string `json:"status"`
}

// Validate validates this created order data
func (m *CreatedOrderData) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateOrderNumber(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CreatedOrderData) validateOrderNumber(formats strfmt.Registry) error {

	if err := validate.RequiredString("order_number", "body", m.OrderNumber); err != nil {
		return err
	}

	return nil
}

func (m *CreatedOrderData) validateStatus(formats strfmt.Registry) error {

	if err := validate.RequiredString("status", "body", m.Status); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this created order data based on context it is used
func (m *CreatedOrderData) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CreatedOrderData) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreatedOrderData) UnmarshalBinary(b []byte) error {
	var res CreatedOrderData
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
