// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// UserData Параметры создания пользователя
//
// swagger:model UserData
type UserData struct {

	// guid
	// Format: uuid
	GUID strfmt.UUID `json:"guid"`

	// Признак удален ли пользователь
	IsDeleted bool `json:"is_deleted"`

	// Имя пользователя
	// Example: Дроздобород Эдуард
	// Required: true
	Name string `json:"name"`

	// Место работы
	// Example: МУП ДЭС
	// Required: true
	Occupation string `json:"occupation"`
}

// Validate validates this user data
func (m *UserData) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateGUID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOccupation(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *UserData) validateGUID(formats strfmt.Registry) error {
	if swag.IsZero(m.GUID) { // not required
		return nil
	}

	if err := validate.FormatOf("guid", "body", "uuid", m.GUID.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *UserData) validateName(formats strfmt.Registry) error {

	if err := validate.RequiredString("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

func (m *UserData) validateOccupation(formats strfmt.Registry) error {

	if err := validate.RequiredString("occupation", "body", m.Occupation); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this user data based on context it is used
func (m *UserData) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UserData) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UserData) UnmarshalBinary(b []byte) error {
	var res UserData
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
