// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// UserEditParams Параметры редактирования пользователя
//
// swagger:model UserEditParams
type UserEditParams struct {

	// Имя пользователя
	// Example: Дроздобород Эдуард
	// Required: true
	Name string `json:"name"`

	// Место работы
	// Example: МУП ДЭС
	// Required: true
	Occupation string `json:"occupation"`
}

// Validate validates this user edit params
func (m *UserEditParams) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOccupation(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *UserEditParams) validateName(formats strfmt.Registry) error {

	if err := validate.RequiredString("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

func (m *UserEditParams) validateOccupation(formats strfmt.Registry) error {

	if err := validate.RequiredString("occupation", "body", m.Occupation); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this user edit params based on context it is used
func (m *UserEditParams) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UserEditParams) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UserEditParams) UnmarshalBinary(b []byte) error {
	var res UserEditParams
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
