// Code generated by go-swagger; DO NOT EDIT.

package other

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"otusgruz/internal/models"
)

// GetAuthOKCode is the HTTP code returned for type GetAuthOK
const GetAuthOKCode int = 200

/*
GetAuthOK Успех

swagger:response getAuthOK
*/
type GetAuthOK struct {
	/*Гуид пользователя.

	 */
	XUser strfmt.UUID `json:"X-User"`
}

// NewGetAuthOK creates GetAuthOK with default headers values
func NewGetAuthOK() *GetAuthOK {

	return &GetAuthOK{}
}

// WithXUser adds the xUser to the get auth o k response
func (o *GetAuthOK) WithXUser(xUser strfmt.UUID) *GetAuthOK {
	o.XUser = xUser
	return o
}

// SetXUser sets the xUser to the get auth o k response
func (o *GetAuthOK) SetXUser(xUser strfmt.UUID) {
	o.XUser = xUser
}

// WriteResponse to the client
func (o *GetAuthOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header X-User

	xUser := o.XUser.String()
	if xUser != "" {
		rw.Header().Set("X-User", xUser)
	}

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// GetAuthUnauthorizedCode is the HTTP code returned for type GetAuthUnauthorized
const GetAuthUnauthorizedCode int = 401

/*
GetAuthUnauthorized Клиентская ошибка

swagger:response getAuthUnauthorized
*/
type GetAuthUnauthorized struct {
}

// NewGetAuthUnauthorized creates GetAuthUnauthorized with default headers values
func NewGetAuthUnauthorized() *GetAuthUnauthorized {

	return &GetAuthUnauthorized{}
}

// WriteResponse to the client
func (o *GetAuthUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// GetAuthInternalServerErrorCode is the HTTP code returned for type GetAuthInternalServerError
const GetAuthInternalServerErrorCode int = 500

/*
GetAuthInternalServerError Серверная ошибка

swagger:response getAuthInternalServerError
*/
type GetAuthInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetAuthInternalServerError creates GetAuthInternalServerError with default headers values
func NewGetAuthInternalServerError() *GetAuthInternalServerError {

	return &GetAuthInternalServerError{}
}

// WithPayload adds the payload to the get auth internal server error response
func (o *GetAuthInternalServerError) WithPayload(payload *models.Error) *GetAuthInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get auth internal server error response
func (o *GetAuthInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAuthInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
