// Code generated by go-swagger; DO NOT EDIT.

package other

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"otusgruz/internal/models"
)

// PostPublicLoginOKCode is the HTTP code returned for type PostPublicLoginOK
const PostPublicLoginOKCode int = 200

/*
PostPublicLoginOK Успешный логин

swagger:response postPublicLoginOK
*/
type PostPublicLoginOK struct {
	/*Гуид пользователя.

	 */
	XUser strfmt.UUID `json:"X-User"`
}

// NewPostPublicLoginOK creates PostPublicLoginOK with default headers values
func NewPostPublicLoginOK() *PostPublicLoginOK {

	return &PostPublicLoginOK{}
}

// WithXUser adds the xUser to the post public login o k response
func (o *PostPublicLoginOK) WithXUser(xUser strfmt.UUID) *PostPublicLoginOK {
	o.XUser = xUser
	return o
}

// SetXUser sets the xUser to the post public login o k response
func (o *PostPublicLoginOK) SetXUser(xUser strfmt.UUID) {
	o.XUser = xUser
}

// WriteResponse to the client
func (o *PostPublicLoginOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header X-User

	xUser := o.XUser.String()
	if xUser != "" {
		rw.Header().Set("X-User", xUser)
	}

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// PostPublicLoginUnauthorizedCode is the HTTP code returned for type PostPublicLoginUnauthorized
const PostPublicLoginUnauthorizedCode int = 401

/*
PostPublicLoginUnauthorized Клиентская ошибка

swagger:response postPublicLoginUnauthorized
*/
type PostPublicLoginUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.DefaultStatusResponse `json:"body,omitempty"`
}

// NewPostPublicLoginUnauthorized creates PostPublicLoginUnauthorized with default headers values
func NewPostPublicLoginUnauthorized() *PostPublicLoginUnauthorized {

	return &PostPublicLoginUnauthorized{}
}

// WithPayload adds the payload to the post public login unauthorized response
func (o *PostPublicLoginUnauthorized) WithPayload(payload *models.DefaultStatusResponse) *PostPublicLoginUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post public login unauthorized response
func (o *PostPublicLoginUnauthorized) SetPayload(payload *models.DefaultStatusResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostPublicLoginUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostPublicLoginNotFoundCode is the HTTP code returned for type PostPublicLoginNotFound
const PostPublicLoginNotFoundCode int = 404

/*
PostPublicLoginNotFound Клиентская ошибка

swagger:response postPublicLoginNotFound
*/
type PostPublicLoginNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.DefaultStatusResponse `json:"body,omitempty"`
}

// NewPostPublicLoginNotFound creates PostPublicLoginNotFound with default headers values
func NewPostPublicLoginNotFound() *PostPublicLoginNotFound {

	return &PostPublicLoginNotFound{}
}

// WithPayload adds the payload to the post public login not found response
func (o *PostPublicLoginNotFound) WithPayload(payload *models.DefaultStatusResponse) *PostPublicLoginNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post public login not found response
func (o *PostPublicLoginNotFound) SetPayload(payload *models.DefaultStatusResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostPublicLoginNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostPublicLoginInternalServerErrorCode is the HTTP code returned for type PostPublicLoginInternalServerError
const PostPublicLoginInternalServerErrorCode int = 500

/*
PostPublicLoginInternalServerError Серверная ошибка

swagger:response postPublicLoginInternalServerError
*/
type PostPublicLoginInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostPublicLoginInternalServerError creates PostPublicLoginInternalServerError with default headers values
func NewPostPublicLoginInternalServerError() *PostPublicLoginInternalServerError {

	return &PostPublicLoginInternalServerError{}
}

// WithPayload adds the payload to the post public login internal server error response
func (o *PostPublicLoginInternalServerError) WithPayload(payload *models.Error) *PostPublicLoginInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post public login internal server error response
func (o *PostPublicLoginInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostPublicLoginInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
