// Code generated by go-swagger; DO NOT EDIT.

package other

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/validate"

	"otusgruz/internal/models"
)

// NewPostPublicSignupParams creates a new PostPublicSignupParams object
//
// There are no default values defined in the spec.
func NewPostPublicSignupParams() PostPublicSignupParams {

	return PostPublicSignupParams{}
}

// PostPublicSignupParams contains all the bound params for the post public signup operation
// typically these are obtained from a http.Request
//
// swagger:parameters PostPublicSignup
type PostPublicSignupParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Параметры логина
	  Required: true
	  In: body
	*/
	Request *models.UserLogin
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPostPublicSignupParams() beforehand.
func (o *PostPublicSignupParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.UserLogin
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("request", "body", ""))
			} else {
				res = append(res, errors.NewParseError("request", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			ctx := validate.WithOperationRequest(r.Context())
			if err := body.ContextValidate(ctx, route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Request = &body
			}
		}
	} else {
		res = append(res, errors.Required("request", "body", ""))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
