// Code generated by go-swagger; DO NOT EDIT.

package other

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostPublicLoginHandlerFunc turns a function with the right signature into a post public login handler
type PostPublicLoginHandlerFunc func(PostPublicLoginParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostPublicLoginHandlerFunc) Handle(params PostPublicLoginParams) middleware.Responder {
	return fn(params)
}

// PostPublicLoginHandler interface for that can handle valid post public login params
type PostPublicLoginHandler interface {
	Handle(PostPublicLoginParams) middleware.Responder
}

// NewPostPublicLogin creates a new http.Handler for the post public login operation
func NewPostPublicLogin(ctx *middleware.Context, handler PostPublicLoginHandler) *PostPublicLogin {
	return &PostPublicLogin{Context: ctx, Handler: handler}
}

/*
	PostPublicLogin swagger:route POST /public/login Other postPublicLogin

Логин пользователя
*/
type PostPublicLogin struct {
	Context *middleware.Context
	Handler PostPublicLoginHandler
}

func (o *PostPublicLogin) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostPublicLoginParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
