// Code generated by go-swagger; DO NOT EDIT.

package user_c_r_u_d

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"otusgruz/internal/models"
)

// DeleteUserGUIDOKCode is the HTTP code returned for type DeleteUserGUIDOK
const DeleteUserGUIDOKCode int = 200

/*
DeleteUserGUIDOK Успешное удаление пользователя

swagger:response deleteUserGuidOK
*/
type DeleteUserGUIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.DefaultStatusResponse `json:"body,omitempty"`
}

// NewDeleteUserGUIDOK creates DeleteUserGUIDOK with default headers values
func NewDeleteUserGUIDOK() *DeleteUserGUIDOK {

	return &DeleteUserGUIDOK{}
}

// WithPayload adds the payload to the delete user Guid o k response
func (o *DeleteUserGUIDOK) WithPayload(payload *models.DefaultStatusResponse) *DeleteUserGUIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete user Guid o k response
func (o *DeleteUserGUIDOK) SetPayload(payload *models.DefaultStatusResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteUserGUIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteUserGUIDInternalServerErrorCode is the HTTP code returned for type DeleteUserGUIDInternalServerError
const DeleteUserGUIDInternalServerErrorCode int = 500

/*
DeleteUserGUIDInternalServerError Серверная ошибка

swagger:response deleteUserGuidInternalServerError
*/
type DeleteUserGUIDInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteUserGUIDInternalServerError creates DeleteUserGUIDInternalServerError with default headers values
func NewDeleteUserGUIDInternalServerError() *DeleteUserGUIDInternalServerError {

	return &DeleteUserGUIDInternalServerError{}
}

// WithPayload adds the payload to the delete user Guid internal server error response
func (o *DeleteUserGUIDInternalServerError) WithPayload(payload *models.Error) *DeleteUserGUIDInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete user Guid internal server error response
func (o *DeleteUserGUIDInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteUserGUIDInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
