// Code generated by go-swagger; DO NOT EDIT.

package user_c_r_u_d

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"otusgruz/internal/models"
)

// DeleteUserGUIDOKCode is the HTTP code returned for type DeleteUserGUIDOK
const DeleteUserGUIDOKCode int = 200

/*
DeleteUserGUIDOK Успешное удаление пользователя

swagger:response deleteUserGuidOK
*/
type DeleteUserGUIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.DefaultStatusResponse `json:"body,omitempty"`
}

// NewDeleteUserGUIDOK creates DeleteUserGUIDOK with default headers values
func NewDeleteUserGUIDOK() *DeleteUserGUIDOK {

	return &DeleteUserGUIDOK{}
}

// WithPayload adds the payload to the delete user Guid o k response
func (o *DeleteUserGUIDOK) WithPayload(payload *models.DefaultStatusResponse) *DeleteUserGUIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete user Guid o k response
func (o *DeleteUserGUIDOK) SetPayload(payload *models.DefaultStatusResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteUserGUIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteUserGUIDBadRequestCode is the HTTP code returned for type DeleteUserGUIDBadRequest
const DeleteUserGUIDBadRequestCode int = 400

/*
DeleteUserGUIDBadRequest Клиентская ошибка

swagger:response deleteUserGuidBadRequest
*/
type DeleteUserGUIDBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteUserGUIDBadRequest creates DeleteUserGUIDBadRequest with default headers values
func NewDeleteUserGUIDBadRequest() *DeleteUserGUIDBadRequest {

	return &DeleteUserGUIDBadRequest{}
}

// WithPayload adds the payload to the delete user Guid bad request response
func (o *DeleteUserGUIDBadRequest) WithPayload(payload *models.Error) *DeleteUserGUIDBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete user Guid bad request response
func (o *DeleteUserGUIDBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteUserGUIDBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteUserGUIDForbiddenCode is the HTTP code returned for type DeleteUserGUIDForbidden
const DeleteUserGUIDForbiddenCode int = 403

/*
DeleteUserGUIDForbidden Клиентская ошибка

swagger:response deleteUserGuidForbidden
*/
type DeleteUserGUIDForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.DefaultStatusResponse `json:"body,omitempty"`
}

// NewDeleteUserGUIDForbidden creates DeleteUserGUIDForbidden with default headers values
func NewDeleteUserGUIDForbidden() *DeleteUserGUIDForbidden {

	return &DeleteUserGUIDForbidden{}
}

// WithPayload adds the payload to the delete user Guid forbidden response
func (o *DeleteUserGUIDForbidden) WithPayload(payload *models.DefaultStatusResponse) *DeleteUserGUIDForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete user Guid forbidden response
func (o *DeleteUserGUIDForbidden) SetPayload(payload *models.DefaultStatusResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteUserGUIDForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteUserGUIDInternalServerErrorCode is the HTTP code returned for type DeleteUserGUIDInternalServerError
const DeleteUserGUIDInternalServerErrorCode int = 500

/*
DeleteUserGUIDInternalServerError Серверная ошибка

swagger:response deleteUserGuidInternalServerError
*/
type DeleteUserGUIDInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteUserGUIDInternalServerError creates DeleteUserGUIDInternalServerError with default headers values
func NewDeleteUserGUIDInternalServerError() *DeleteUserGUIDInternalServerError {

	return &DeleteUserGUIDInternalServerError{}
}

// WithPayload adds the payload to the delete user Guid internal server error response
func (o *DeleteUserGUIDInternalServerError) WithPayload(payload *models.Error) *DeleteUserGUIDInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete user Guid internal server error response
func (o *DeleteUserGUIDInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteUserGUIDInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
