// Code generated by go-swagger; DO NOT EDIT.

package user_c_r_u_d

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// NewGetUserGUIDParams creates a new GetUserGUIDParams object
//
// There are no default values defined in the spec.
func NewGetUserGUIDParams() GetUserGUIDParams {

	return GetUserGUIDParams{}
}

// GetUserGUIDParams contains all the bound params for the get user GUID operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetUserGUID
type GetUserGUIDParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*guid пользователя
	  Required: true
	  In: path
	*/
	GUID strfmt.UUID
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetUserGUIDParams() beforehand.
func (o *GetUserGUIDParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rGUID, rhkGUID, _ := route.Params.GetOK("guid")
	if err := o.bindGUID(rGUID, rhkGUID, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindGUID binds and validates parameter GUID from path.
func (o *GetUserGUIDParams) bindGUID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	// Format: uuid
	value, err := formats.Parse("uuid", raw)
	if err != nil {
		return errors.InvalidType("guid", "path", "strfmt.UUID", raw)
	}
	o.GUID = *(value.(*strfmt.UUID))

	if err := o.validateGUID(formats); err != nil {
		return err
	}

	return nil
}

// validateGUID carries on validations for parameter GUID
func (o *GetUserGUIDParams) validateGUID(formats strfmt.Registry) error {

	if err := validate.FormatOf("guid", "path", "uuid", o.GUID.String(), formats); err != nil {
		return err
	}
	return nil
}
