// Code generated by go-swagger; DO NOT EDIT.

package user_c_r_u_d

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"otusgruz/internal/models"
)

// GetUserGUIDOKCode is the HTTP code returned for type GetUserGUIDOK
const GetUserGUIDOKCode int = 200

/*
GetUserGUIDOK Успешное получение данных по пользователю

swagger:response getUserGuidOK
*/
type GetUserGUIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.UserData `json:"body,omitempty"`
}

// NewGetUserGUIDOK creates GetUserGUIDOK with default headers values
func NewGetUserGUIDOK() *GetUserGUIDOK {

	return &GetUserGUIDOK{}
}

// WithPayload adds the payload to the get user Guid o k response
func (o *GetUserGUIDOK) WithPayload(payload *models.UserData) *GetUserGUIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get user Guid o k response
func (o *GetUserGUIDOK) SetPayload(payload *models.UserData) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetUserGUIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetUserGUIDBadRequestCode is the HTTP code returned for type GetUserGUIDBadRequest
const GetUserGUIDBadRequestCode int = 400

/*
GetUserGUIDBadRequest Клиентская ошибка

swagger:response getUserGuidBadRequest
*/
type GetUserGUIDBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetUserGUIDBadRequest creates GetUserGUIDBadRequest with default headers values
func NewGetUserGUIDBadRequest() *GetUserGUIDBadRequest {

	return &GetUserGUIDBadRequest{}
}

// WithPayload adds the payload to the get user Guid bad request response
func (o *GetUserGUIDBadRequest) WithPayload(payload *models.Error) *GetUserGUIDBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get user Guid bad request response
func (o *GetUserGUIDBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetUserGUIDBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetUserGUIDForbiddenCode is the HTTP code returned for type GetUserGUIDForbidden
const GetUserGUIDForbiddenCode int = 403

/*
GetUserGUIDForbidden Клиентская ошибка

swagger:response getUserGuidForbidden
*/
type GetUserGUIDForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.DefaultStatusResponse `json:"body,omitempty"`
}

// NewGetUserGUIDForbidden creates GetUserGUIDForbidden with default headers values
func NewGetUserGUIDForbidden() *GetUserGUIDForbidden {

	return &GetUserGUIDForbidden{}
}

// WithPayload adds the payload to the get user Guid forbidden response
func (o *GetUserGUIDForbidden) WithPayload(payload *models.DefaultStatusResponse) *GetUserGUIDForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get user Guid forbidden response
func (o *GetUserGUIDForbidden) SetPayload(payload *models.DefaultStatusResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetUserGUIDForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetUserGUIDInternalServerErrorCode is the HTTP code returned for type GetUserGUIDInternalServerError
const GetUserGUIDInternalServerErrorCode int = 500

/*
GetUserGUIDInternalServerError Серверная ошибка

swagger:response getUserGuidInternalServerError
*/
type GetUserGUIDInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetUserGUIDInternalServerError creates GetUserGUIDInternalServerError with default headers values
func NewGetUserGUIDInternalServerError() *GetUserGUIDInternalServerError {

	return &GetUserGUIDInternalServerError{}
}

// WithPayload adds the payload to the get user Guid internal server error response
func (o *GetUserGUIDInternalServerError) WithPayload(payload *models.Error) *GetUserGUIDInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get user Guid internal server error response
func (o *GetUserGUIDInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetUserGUIDInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
