// Code generated by go-swagger; DO NOT EDIT.

package user_c_r_u_d

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"otusgruz/internal/models"
)

// PatchUserGUIDOKCode is the HTTP code returned for type PatchUserGUIDOK
const PatchUserGUIDOKCode int = 200

/*
PatchUserGUIDOK Успешное изменение данных по пользователю

swagger:response patchUserGuidOK
*/
type PatchUserGUIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.DefaultStatusResponse `json:"body,omitempty"`
}

// NewPatchUserGUIDOK creates PatchUserGUIDOK with default headers values
func NewPatchUserGUIDOK() *PatchUserGUIDOK {

	return &PatchUserGUIDOK{}
}

// WithPayload adds the payload to the patch user Guid o k response
func (o *PatchUserGUIDOK) WithPayload(payload *models.DefaultStatusResponse) *PatchUserGUIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the patch user Guid o k response
func (o *PatchUserGUIDOK) SetPayload(payload *models.DefaultStatusResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PatchUserGUIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PatchUserGUIDBadRequestCode is the HTTP code returned for type PatchUserGUIDBadRequest
const PatchUserGUIDBadRequestCode int = 400

/*
PatchUserGUIDBadRequest Клиентская ошибка

swagger:response patchUserGuidBadRequest
*/
type PatchUserGUIDBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPatchUserGUIDBadRequest creates PatchUserGUIDBadRequest with default headers values
func NewPatchUserGUIDBadRequest() *PatchUserGUIDBadRequest {

	return &PatchUserGUIDBadRequest{}
}

// WithPayload adds the payload to the patch user Guid bad request response
func (o *PatchUserGUIDBadRequest) WithPayload(payload *models.Error) *PatchUserGUIDBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the patch user Guid bad request response
func (o *PatchUserGUIDBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PatchUserGUIDBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PatchUserGUIDForbiddenCode is the HTTP code returned for type PatchUserGUIDForbidden
const PatchUserGUIDForbiddenCode int = 403

/*
PatchUserGUIDForbidden Клиентская ошибка

swagger:response patchUserGuidForbidden
*/
type PatchUserGUIDForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.DefaultStatusResponse `json:"body,omitempty"`
}

// NewPatchUserGUIDForbidden creates PatchUserGUIDForbidden with default headers values
func NewPatchUserGUIDForbidden() *PatchUserGUIDForbidden {

	return &PatchUserGUIDForbidden{}
}

// WithPayload adds the payload to the patch user Guid forbidden response
func (o *PatchUserGUIDForbidden) WithPayload(payload *models.DefaultStatusResponse) *PatchUserGUIDForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the patch user Guid forbidden response
func (o *PatchUserGUIDForbidden) SetPayload(payload *models.DefaultStatusResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PatchUserGUIDForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PatchUserGUIDInternalServerErrorCode is the HTTP code returned for type PatchUserGUIDInternalServerError
const PatchUserGUIDInternalServerErrorCode int = 500

/*
PatchUserGUIDInternalServerError Серверная ошибка

swagger:response patchUserGuidInternalServerError
*/
type PatchUserGUIDInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPatchUserGUIDInternalServerError creates PatchUserGUIDInternalServerError with default headers values
func NewPatchUserGUIDInternalServerError() *PatchUserGUIDInternalServerError {

	return &PatchUserGUIDInternalServerError{}
}

// WithPayload adds the payload to the patch user Guid internal server error response
func (o *PatchUserGUIDInternalServerError) WithPayload(payload *models.Error) *PatchUserGUIDInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the patch user Guid internal server error response
func (o *PatchUserGUIDInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PatchUserGUIDInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
