// Code generated by go-swagger; DO NOT EDIT.

package user_c_r_u_d

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"

	"otusgruz/internal/models"
)

// NewPatchUserGUIDParams creates a new PatchUserGUIDParams object
//
// There are no default values defined in the spec.
func NewPatchUserGUIDParams() PatchUserGUIDParams {

	return PatchUserGUIDParams{}
}

// PatchUserGUIDParams contains all the bound params for the patch user GUID operation
// typically these are obtained from a http.Request
//
// swagger:parameters PatchUserGUID
type PatchUserGUIDParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*guid пользователя
	  Required: true
	  In: path
	*/
	GUID strfmt.UUID
	/*Параметры создания пользователя
	  Required: true
	  In: body
	*/
	Request *models.UserCreateParams
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPatchUserGUIDParams() beforehand.
func (o *PatchUserGUIDParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rGUID, rhkGUID, _ := route.Params.GetOK("guid")
	if err := o.bindGUID(rGUID, rhkGUID, route.Formats); err != nil {
		res = append(res, err)
	}

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.UserCreateParams
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("request", "body", ""))
			} else {
				res = append(res, errors.NewParseError("request", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			ctx := validate.WithOperationRequest(r.Context())
			if err := body.ContextValidate(ctx, route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Request = &body
			}
		}
	} else {
		res = append(res, errors.Required("request", "body", ""))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindGUID binds and validates parameter GUID from path.
func (o *PatchUserGUIDParams) bindGUID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	// Format: uuid
	value, err := formats.Parse("uuid", raw)
	if err != nil {
		return errors.InvalidType("guid", "path", "strfmt.UUID", raw)
	}
	o.GUID = *(value.(*strfmt.UUID))

	if err := o.validateGUID(formats); err != nil {
		return err
	}

	return nil
}

// validateGUID carries on validations for parameter GUID
func (o *PatchUserGUIDParams) validateGUID(formats strfmt.Registry) error {

	if err := validate.FormatOf("guid", "path", "uuid", o.GUID.String(), formats); err != nil {
		return err
	}
	return nil
}
