// Code generated by go-swagger; DO NOT EDIT.

package user_c_r_u_d

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PatchUserGUIDHandlerFunc turns a function with the right signature into a patch user GUID handler
type PatchUserGUIDHandlerFunc func(PatchUserGUIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PatchUserGUIDHandlerFunc) Handle(params PatchUserGUIDParams) middleware.Responder {
	return fn(params)
}

// PatchUserGUIDHandler interface for that can handle valid patch user GUID params
type PatchUserGUIDHandler interface {
	Handle(PatchUserGUIDParams) middleware.Responder
}

// NewPatchUserGUID creates a new http.Handler for the patch user GUID operation
func NewPatchUserGUID(ctx *middleware.Context, handler PatchUserGUIDHandler) *PatchUserGUID {
	return &PatchUserGUID{Context: ctx, Handler: handler}
}

/*
	PatchUserGUID swagger:route PATCH /user/{guid} User CRUD patchUserGuid

Изменение информации по пользователю
*/
type PatchUserGUID struct {
	Context *middleware.Context
	Handler PatchUserGUIDHandler
}

func (o *PatchUserGUID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPatchUserGUIDParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
