// Code generated by go-swagger; DO NOT EDIT.

package orders

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostOrderNewHandlerFunc turns a function with the right signature into a post order new handler
type PostOrderNewHandlerFunc func(PostOrderNewParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostOrderNewHandlerFunc) Handle(params PostOrderNewParams) middleware.Responder {
	return fn(params)
}

// PostOrderNewHandler interface for that can handle valid post order new params
type PostOrderNewHandler interface {
	Handle(PostOrderNewParams) middleware.Responder
}

// NewPostOrderNew creates a new http.Handler for the post order new operation
func NewPostOrderNew(ctx *middleware.Context, handler PostOrderNewHandler) *PostOrderNew {
	return &PostOrderNew{Context: ctx, Handler: handler}
}

/*
	PostOrderNew swagger:route POST /order/new Orders postOrderNew

Создание заказа пользователя
*/
type PostOrderNew struct {
	Context *middleware.Context
	Handler PostOrderNewHandler
}

func (o *PostOrderNew) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostOrderNewParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
