// Code generated by go-swagger; DO NOT EDIT.

package orders

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"otusgruz/internal/models"
)

// PostOrderNewOKCode is the HTTP code returned for type PostOrderNewOK
const PostOrderNewOKCode int = 200

/*
PostOrderNewOK Создание заказа

swagger:response postOrderNewOK
*/
type PostOrderNewOK struct {

	/*
	  In: Body
	*/
	Payload *models.CreatedOrderData `json:"body,omitempty"`
}

// NewPostOrderNewOK creates PostOrderNewOK with default headers values
func NewPostOrderNewOK() *PostOrderNewOK {

	return &PostOrderNewOK{}
}

// WithPayload adds the payload to the post order new o k response
func (o *PostOrderNewOK) WithPayload(payload *models.CreatedOrderData) *PostOrderNewOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post order new o k response
func (o *PostOrderNewOK) SetPayload(payload *models.CreatedOrderData) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostOrderNewOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostOrderNewUnauthorizedCode is the HTTP code returned for type PostOrderNewUnauthorized
const PostOrderNewUnauthorizedCode int = 401

/*
PostOrderNewUnauthorized Клиентская ошибка

swagger:response postOrderNewUnauthorized
*/
type PostOrderNewUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.DefaultStatusResponse `json:"body,omitempty"`
}

// NewPostOrderNewUnauthorized creates PostOrderNewUnauthorized with default headers values
func NewPostOrderNewUnauthorized() *PostOrderNewUnauthorized {

	return &PostOrderNewUnauthorized{}
}

// WithPayload adds the payload to the post order new unauthorized response
func (o *PostOrderNewUnauthorized) WithPayload(payload *models.DefaultStatusResponse) *PostOrderNewUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post order new unauthorized response
func (o *PostOrderNewUnauthorized) SetPayload(payload *models.DefaultStatusResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostOrderNewUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostOrderNewNotFoundCode is the HTTP code returned for type PostOrderNewNotFound
const PostOrderNewNotFoundCode int = 404

/*
PostOrderNewNotFound Клиентская ошибка

swagger:response postOrderNewNotFound
*/
type PostOrderNewNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.DefaultStatusResponse `json:"body,omitempty"`
}

// NewPostOrderNewNotFound creates PostOrderNewNotFound with default headers values
func NewPostOrderNewNotFound() *PostOrderNewNotFound {

	return &PostOrderNewNotFound{}
}

// WithPayload adds the payload to the post order new not found response
func (o *PostOrderNewNotFound) WithPayload(payload *models.DefaultStatusResponse) *PostOrderNewNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post order new not found response
func (o *PostOrderNewNotFound) SetPayload(payload *models.DefaultStatusResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostOrderNewNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostOrderNewInternalServerErrorCode is the HTTP code returned for type PostOrderNewInternalServerError
const PostOrderNewInternalServerErrorCode int = 500

/*
PostOrderNewInternalServerError Серверная ошибка

swagger:response postOrderNewInternalServerError
*/
type PostOrderNewInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostOrderNewInternalServerError creates PostOrderNewInternalServerError with default headers values
func NewPostOrderNewInternalServerError() *PostOrderNewInternalServerError {

	return &PostOrderNewInternalServerError{}
}

// WithPayload adds the payload to the post order new internal server error response
func (o *PostOrderNewInternalServerError) WithPayload(payload *models.Error) *PostOrderNewInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post order new internal server error response
func (o *PostOrderNewInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostOrderNewInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
