apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuber-dp
  labels:
    app: kuber-dp
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      env: v1
  template:
    metadata:
      labels:
        env: v1
    spec:
      containers:
      - name: kuber-app
        image: nikolaygr/otusgruz:v0.15
        envFrom:
         - configMapRef:
            name: conf-map
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: helm-psql-3-postgresql               
              key: postgres-password
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /api/public/health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 3