apiVersion: batch/v1
kind: Job
metadata:
  name:  migrate-postgres
spec:
  template:
    spec:
      containers:
      - name: migrate-postgres
        image: nikolaygr/otusgruz:v0.1
        command: ["/app", "postgres", "up"]
      restartPolicy: Never
  backoffLimit: 4