apiVersion: batch/v1
kind: Job
metadata:
  name:  migrate-postgres
spec:
  template:
    spec:
      containers:
      - name: migrate-postgres
        image: nikolaygr/otusgruz:v0.5
        command: ["/otusgruz", "postgres", "up"]
        env:
        - name: POSTGRES_HOST 
          valueFrom:
            configMapKeyRef:
              name: conf-map          
              key: postgres_host
        - name: POSTGRES_PORT 
          valueFrom:
            configMapKeyRef:
              name: conf-map          
              key: postgres_port
        - name: POSTGRES_DB_NAME 
          valueFrom:
            configMapKeyRef:
              name: conf-map          
              key: postgres_db_name
        - name: POSTGRES_USER 
          valueFrom:
            configMapKeyRef:
              name: conf-map          
              key: postgres_user
        - name: POSTGRES_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: conf-map                  
              key: postgres_password
      restartPolicy: Never   
  backoffLimit: 4