apiVersion: batch/v1
kind: Job
metadata:
  name:  migrate-postgres
spec:
  template:
    spec:
      containers:
      - name: migrate-postgres
        image: nikolaygr/otusgruz:v0.10
        command: ["/otusgruz", "postgres", "up"]
        envFrom:
         - configMapRef:
            name: conf-map
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: helm-psql-2-postgresql               
              key: postgres-password
      restartPolicy: Never   
  backoffLimit: 4