apiVersion: v1
kind: Service
metadata:
  name: kuber-service
spec:
  selector:
    env: v1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
    - protocol: TCP
      name: metrics
      port: 80
      targetPort: 8080
  type: ClusterIP